// list on left should be list of places generated by google places API
// right should show locations of those on a map with markers

import React, {Component} from 'react';
import {connect} from 'react-redux';
import {Link} from 'react-router-dom';

// import components

// import functions
import {getEventInfo, getPlaces} from './../../../ducks/reducer';
import googleMapsService from './../../../utility/googleMapsService';

// import css
import './MapView.css';
const google = window.google;

class MapView extends Component {
    constructor(props) {
        super(props);
    }

    componentDidMount() {
        // init map
        this.props.getEventInfo().then(() => this.props.getPlaces({
            location: {
                lat: this.props.reactEvent.venue.lat,
                lng: this.props.reactEvent.venue.lon
            },
            meters: 16000,
            type: 'accounting'
        }
    )).then(() => googleMapsService.initMap.call(this, this.gmap, this.props.reactEvent))
        // googleMapsService.initMap.call(this, this.gmap, this.props.reactEvent)
        // google.maps.event.trigger(this.map, 'resize');
        // var marker = new google.maps.Marker({
        //     map: this.map,
        //     position: {
        //         lat: 32.8237831,
        //         lng: -96.7702054
        //     },
        //     animation: google.maps.Animation.DROP,
        // })
    }
    componentWillReceiveProps() {
        // create markers
    }
    render() {
        return (
            <div className="container" >
                <div className="map-container">
                    <div id="gmap" ref={ref => (this.gmap = ref)} />
                </div>
                <div>
                    Other content
                </div>
            </div>
        )
    }
}
const mapStateToProps = state => state
export default connect(mapStateToProps, {getEventInfo, getPlaces}) (MapView);